version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: api-mutant
    hostname: app-mutant
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    volumes:
    - ./mongodb/data/db
    ports:
    - "27017:27017"


