version: '3'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "mutant"
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "secret"
    ports:
      - '13306:3306'

  mutant-app:
    image: springboot-container-mutant
    ports:
      - 8082:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql