version: "3"
services:
  mymongodb:
    image: mongo:latest
    container_name: "mymongodb"
    ports:
      - 27017:27017
  springboot-mutant-mongodb:
    image: springboot-mongodb:1.0
    container_name: springboot-mutant-mongodb
    build:
      dockerfile : DockerFile
    ports:
      - 8080:8080
    links:
      - mymongodb